#theme: jekyll-theme-architect
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
#footer_content: "Handcrafted with &hearts; @ YU CLoud Solutions  <a href='//forms.gle/FMcLuq29gYEHpWC6A'>Report a Problem</a>  <a href='//forms.gle/SbCM6tL8KP12AaU1A'>Feedback</a>   <a href='//wa.me/+919412580180'>Whatsapp</a> "
search_enabled: false
title: GStatic - Static Site Hosting
name: "GStatic"
description: "A platform to deploy static websites in a dead simple manner"
twitter:
  username: "gstatic_tech"
og_image: /img/logo.png  

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-165448469-1"
    anonymize_ip: false # default

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/gstatic_tech"
    - label: "Github"
      icon:  "fab fa-fw fa-github" 
      url: "https://github.com/devansh42/yu-cli.git"
    - label: "npm"
      icon: "fab fa-fw fa-npm"
      url: "https://npmjs.org/yu-gstatic"  

logo: "/img/logo.png"

aux_links:
  "GStatic":
    - "//gstatic.tech"
  "Github":
    - "//github.com/devansh42/yu-cli.git"
  "npm":
    - "//npmjs.com/package/yu-gstatic"
