theme: jekyll-theme-architect
remote_theme: pmarsceill/just-the-docs
footer_content: "Handcrafted with &hearts; @ YU CLoud Solutions"
search_enabled: false
title: GStatic - Static Site Hosting
aux_links:
  "GStatic":
    - "//gstatic.tech"
